#!/usr/bin/env bash
# backend-specific -- invoke a backend specific command for the current graph
# Usage: backend-specific COMMAND [ARG...]
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-10
set -eu

[ $# -gt 0 ] || usage "$0" "No COMMAND given"

Cmd=$1; shift
if backendCmd=$(find-backend-specific "$Cmd"); then
    exec "$backendCmd" "$@"
else
    case $! in
        1)
            error "$Cmd: not available for $Backend backend"
            ;;
        2)
            error "PWD is not a graph or cannot determine its backend"
            ;;
    esac
fi
