#!/usr/bin/env bash
# find-backend-specific -- find a backend specific command for the current graph
# Usage: find-backend-specific COMMAND
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-05-15
set -eu

[ $# -gt 0 ] || usage "$0" "No COMMAND given"

if [ -r .graphd.backend ] && Backend=$(cat .graphd.backend); then
    Cmd=$1; shift
    if type "$Cmd@$Backend" &>/dev/null; then
        echo "$Cmd@$Backend"
        exit
    else
        exit 1
    fi
else
    exit 2
fi
