.build/*.js                                             $GRAPHDDIR/giraph/
template                                                $GRAPHDDIR/giraph/

# FIXME: use env var to share where to put jars in
run-smallgraph-on-giraph                                $GRAPHDDIR/giraph/
backend/target/smallgraphs-giraph-backend-*-jar-with-dependencies.jar $JARDIR/smallgraphs-giraph.jar

graphd-import-rdf@giraph                                $TOOLSDIR/
