#!/usr/bin/env bash
# graphd-import-rdf@giraph -- Import RDF NTriples
# Usage: graphd import-rdf NTRIPLESFILE...
# 
# Import RDF NTriples files to the graph at current working directory
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-03-18
set -eu

RDFUtilJar="$JARDIR"/graphd-rdfutil.jar


# process arguments
[ $# -ge 0 ] || { sed -n '2,/^#$/ s/^# //p' <"$0"; exit 2; }

graphName=`basename "$PWD"`


cat -- "$@" |
{
    mkdir -p map

    # encode/load RDF N-Triples and transform it to vertex-wise JSON graph and derive a decoding schema
    java -cp "$RDFUtilJar" edu.stanford.smallgraphs.util.RDFGraphTransformer \
        -g map -d dict \
        -importUnencodedNTriples - \
        -outputJSONVertexGraph jsonVertices \
        -deriveSchema codingSchema.json
        #

    # create a graph descriptor
    if ! [ -e graphd.json ]; then
        cat >graphd.json <<-EOF
	{
	  "giraph": {
	    "hdfsPath": "graphs/$graphName",
	    "codingSchemaPath": "codingSchema.json"
	  }
	}
	EOF
    fi

    # format JSONs
    format-json codingSchema.json
}
