#!/usr/bin/env bash
# import-rdf
# Usage: import-rdf GRAPHDIR [RDFFILE]...
# 
# Import RDF files to the given GRAPHDIR.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-03-18
set -eu

Self=`readlink -f "$0"`
Here=`dirname "$Self"`

jars=("$Here"/../../tools/rdfutil/target/smallgraphs-rdfutil-*-jar-with-dependencies.jar)
RDFUtilJar=${jars[0]}


# process arguments
[ $# -ge 1 ] || { sed -n '2,/^#$/ s/^# //p' <"$0"; exit 2; }
GraphBase=$1; shift

graphName=`basename "$GraphBase"`


cat -- "$@" |
{
    mkdir -p "$GraphBase"/map
    cd "$GraphBase"

    # encode/load RDF N-Triples and transform it to vertex-wise JSON graph and derive a decoding schema
    java -cp "$RDFUtilJar" edu.stanford.smallgraphs.util.RDFGraphTransformer \
        -g map -d dict \
        -importUnencodedNTriples - \
        -outputJSONVertexGraph jsonVertices \
        -deriveSchema codingSchema.json
        #

    # create a graph descriptor
    if ! [ -e graphd.json ]; then
        cat >graphd.json <<-EOF
	{
	  "giraph": {
	    "hdfsPath": "graphs/$graphName",
	    "codingSchemaPath": "codingSchema.json"
	  }
	}
	EOF
    fi

    # format JSONs
    coffee -e '
    fs = require("fs")
    for f in "codingSchema.json".split /\s+/
        fs.writeFileSync f, (JSON.stringify (JSON.parse fs.readFileSync f), null, 2)
    '
}
